/**
 * *************************************************************************
 *    This file is part of GTuring.                                        *
 *                                                                         *
 *  GTuring is free software: you can redistribute it and/or modify        *
 *  it under the terms of the GNU General Public License as published by   *
 *  the Free Software Foundation, either version 3 of the License, or      *
 *  (at your option) any later version.                                    *
 *                                                                         *
 *  GTuring is distributed in the hope that it will be useful,             *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *  GNU General Public License for more details.                           *
 *                                                                         *
 *  You should have received a copy of the GNU General Public License      *
 *  along with GTuring.  If not, see <http://www.gnu.org/licenses/>.       *
 *                                                                         *
 * *************************************************************************
 */
package gnieh.turing
package compiler

import java.io.File

import frontend._
import util._
import parser.TMDLFileParser

import scopt.immutable.OptionParser

/**
 * This is the main method, entry point for the gniehturing compiler
 *
 * @author Lucas Satabin
 *
 */
object GniehTuringC extends App {

  val optionsParser =
    new OptionParser[Options](Some("gtc"), Some("3.0"), true) {
      def options = Seq(
        help("h", "help", "display this help"),
        flag("v", "verbose", "enable the verbose mode") {
          c => c.copy(verbose = true)
        },
        opt("o", "output", "sets the output file name (default out.tbc)") {
          (s, o) => o.copy(outFile = new File(s))
        },
        opt("mp", "machinepath",
          "specify the machine path, all paths must be separated by a "
            + File.pathSeparator) {
            (s, o) =>
              o.copy(path = s.split(File.pathSeparator).map(f => new File(f)).toList)
          },
        opt("bc", "bytecode", "the version of generated bytecode (default 2.1)") {
          (s, o) => o.copy(bcVersion = s)
        },
        flag("no-output", "do not generate the compiled file, just print it to the console") {
          o => o.copy(generateOutput = false)
        },
        arglist("<file>...", ".tmdl files to compile") {
          (f, o) => o.copy(files = new File(f) :: o.files)
        })

      override def showUsage = println(usage)
    }

  optionsParser.parse(args, Options()) match {
    case Some(options) =>
      // create the compiler
      val compiler =
        new Compiler(new ConsoleReporter with CountingReporter, options) {
          self =>

          object tableBuilder extends SymbolTableBuilder {
            val reporter = self.reporter
            val options = self.options
          }

          object referenceChecker extends ReferenceChecker {
            val reporter = self.reporter
            val options = self.options
          }

          object actionsSimplifier extends ActionsSimplifier {
            val reporter = self.reporter
            val options = self.options
          }

          val frontendSteps = List(tableBuilder, referenceChecker, actionsSimplifier)
        }

      // and do the job
      compiler.gogogo

    case None =>
    // wrong option or argument, the help message was displayed
  }

}